# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170624_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 24, 13, 25, 8, 570583)),
        ),
    ]
