# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170624_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 24, 14, 46, 5, 781604)),
        ),
    ]
